region = "us"
kube = "rnates"
port = 3000

[config]
enabled = true
port = 8080
ratio = 3.14
names = ["a", "b", 1, false]

[config.tls]
cert_path = "/etc/cert.pem"

[config.example.block]
name = "My Name"
