name: CI CSharp

on:
  push:
    branches: ["**"]
  pull_request:
    paths:
      - 'implementations/csharp/**'
      - '.github/workflows/ci-csharp.yml'
      - 'e2e/**'

jobs:
  csharp:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: implementations/csharp
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Linux'
        run: sudo apt-get update
      - if: runner.os == 'Linux'
        run: sudo apt-get install -y mono-mcs
      - if: runner.os == 'macOS'
        run: brew install mono
      - run: mcs -out:test_bin src/*.cs test/Test.cs
      - run: mono test_bin
