name: CI CSharp

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  csharp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: implementations/csharp
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install -y mono-mcs
      - run: mcs -out:test_bin src/*.cs test/Test.cs
      - run: mono test_bin
