name: CI Crystal

on:
  push:
    branches: ["**"]
  pull_request:
    paths:
      - 'implementations/crystal/**'
      - '.github/workflows/ci-crystal.yml'
      - 'e2e/**'

jobs:
  crystal:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: implementations/crystal
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - run: crystal spec
