name: CI CSharp

on:
  push:
    branches: ["**"]
  pull_request:
    paths:
      - 'implementations/csharp/**'
      - '.github/workflows/ci-csharp.yml'
      - 'e2e/**'

jobs:
  csharp:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: implementations/csharp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet run --nologo --configuration Release --project RclE2E.csproj
