name: CI D

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  d:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: implementations/d
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc-latest
      - run: ldc2 -i -Isource source/rcl/package.d test/test.d -of=test_bin
      - run: ./test_bin
