name: CI OCaml

on:
  push:
    branches: ["**"]
  pull_request:
    paths:
      - 'implementations/ocaml/**'
      - '.github/workflows/ci-ocaml.yml'
      - 'e2e/**'

jobs:
  ocaml:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: implementations/ocaml
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.1"
      - run: opam exec -- ocamlc -I +str -I +unix str.cma unix.cma rcl.ml test.ml -o test_bin
      - run: opam exec -- ./test_bin
