name: CI OCaml

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  ocaml:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: implementations/ocaml
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.1"
      - run: ocamlc str.cma unix.cma rcl.ml test.ml -o test_bin
      - run: ./test_bin
