name: CI Swift

on:
  push:
    branches: ["**"]
  pull_request:
    paths:
      - 'implementations/swift/**'
      - '.github/workflows/ci-swift.yml'
      - 'e2e/**'

jobs:
  swift:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: implementations/swift
    steps:
      - uses: actions/checkout@v4
      - run: swift test
